sc show <user> added

diff --git a/sip_router/scripts/sc b/sip_router/scripts/sc
--- a/sip_router/scripts/sc
+++ b/sip_router/scripts/sc
@@ -1,6 +1,6 @@
 #!/bin/sh 
 #
-# $Id: sc,v 1.26 2002/09/02 19:45:26 jku Exp $
+# $Id: sc,v 1.27 2002/09/08 16:13:25 jku Exp $
 #
 # sc: ser control; tool for maintaining ser's databases
 #
@@ -132,6 +132,29 @@ ul_dump()
 	fi
 	cat > $SER_FIFO <<EOF
 :ul_dump:$name
+
+EOF
+	cat < $path
+	rm $path
+}
+
+ul_show_contact() # params: <table> <username>
+{
+	name=ser_receiver_$$
+	path=/tmp/$name
+	if [ ! -w $SER_FIFO ]; then
+		echo "Error opening ser's FIFO $SER_FIFO"
+		exit 1
+	fi
+	mkfifo $path
+	if [ $? -ne 0 ] ; then
+		echo "error opening read fifo $path"
+		exit 1
+	fi
+	cat > $SER_FIFO <<EOF
+:ul_show_contact:$name
+$1
+$2
 
 EOF
 	cat < $path
@@ -537,7 +560,13 @@ case $1 in
 		;;
 
 	show)
-		ul_dump
+		shift
+	
+		if [ $# -eq 1 ] ; then
+			ul_show_contact $USRLOC $1
+		else
+			ul_dump
+		fi
 		exit $?
 		;;
 
