Check if ser configuration is valid before restarting the server. If configuration is broken, fix it, then do again:
/etc/init.d/ser restart

Valid for restarts only (start/stop not affected).

diff --git a/sip_router/debian/ser.init b/sip_router/debian/ser.init
--- a/sip_router/debian/ser.init
+++ b/sip_router/debian/ser.init
@@ -10,7 +10,7 @@
 # Version:	@(#)skeleton  1.8  03-Mar-1998  miquels@cistron.nl
 #
 #  adapted for ser by Andrei Pelinescu-Onciul <pelinescu-onciul@fokus.gmd.de>
-# $Id: ser.init,v 1.2 2003/06/30 15:48:44 andrei Exp $
+# $Id: ser.init,v 1.3 2004/01/23 10:53:17 agprojects Exp $
 
 
 PATH=/sbin:/bin:/usr/sbin:/usr/bin
@@ -55,6 +55,13 @@ case "$1" in
 	#	option to the "reload" entry above. If not, "force-reload" is
 	#	just the same as "restart".
 	#
+	# Check if ser configuration is valid before restarting the server
+	out=`($DAEMON -c >/dev/null || true) 2>&1`
+	if [ "$out" != 'config file ok, exiting...' ]; then
+	    echo -e "\nThere are errors in the configuration file. Please fix them first"
+	    echo -e "\n$out\n"
+	    exit 0
+	fi
 	echo -n "Restarting $DESC: $NAME"
 	start-stop-daemon --oknodo --stop --quiet --pidfile \
 		$PIDFILE --exec $DAEMON
